name: cui_build
on:
  push:
    branches:
      - 'main'
      - 'develop'
    paths:
      - 'src/*'
      - '.github/workflows/cui_build.yml'

jobs:
  build:
    name: Build Rust (on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - x86_64-pc-windows-msvc
        include:
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            ls_command: ls
            file_extention: ""
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            ls_command: dir
            file_extention: ".exe"
    env: 
      RUST_BACKTRACE: full
      TZ: 'Asia/Tokyo'
      TOOL_NAME: 'csv-to-sql'
    steps:
      -
        name: Fetch Sources
        uses: actions/checkout@v3
      -
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.os }}-${{ matrix.target }}
      -
        name: Install musl tools
        if : matrix.target == 'x86_64-unknown-linux-musl'
        run: |
          rustup target add x86_64-unknown-linux-musl
          sudo apt install -qq -y musl-tools --no-install-recommends
      -
        name: Get cargo metadata json for version information
        id: cargo-metadate
        shell: bash
        run: |
          cargoMetadata=$(cargo metadata --no-deps)
          version=$(fromJson(${cargoMetadata}).packages[0].version)
          echo "cargoMetadata=${cargoMetadata}" >> $GITHUB_OUTPUT
          echo "version=${version}" >> $GITHUB_OUTPUT
      -
        name: Exec cargo command
        run: cargo build --release --target=${{ matrix.target }}
      -
        name: Check release Directory
        run: |
          ${{ matrix.ls_command }} target/${{ matrix.target }}/release/
      -
        name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.TOOL_NAME }}-v${{ steps.cargo-metadate.outputs.version }}-build-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/${{ env.TOOL_NAME }}${{ matrix.file_extention }}
